### ISSUE TITLE
[Suggestions] Make it more accesible to the end user

### ISSUE THREAD

**Issue by CRHStudios** [Ts-Pytham/Reproductor-de-Musica#1]
This is a good begining for the project, there is a couple of suggestions for the end users:

1. Make the left menu font in bold.
2. In the bottom of the current playlist or where you want, show the total time of it.
3. Double click to play a song on the playlist.
4. Put a secuential number before the name of the songs.
5. If you can read the m3u data from the song, show that info in the playlist.

**Comment by Ts-Pytham** [comment]
Hello CRHStudios! Thank you for your suggestion, i'm adding the new functions suggested by you!

**Comment by Ts-Pytham** [comment]
Hello CRHStudios, in the next update i there will be added your suggestion.
